"""fix chat message foreign key

Revision ID: ff87ccadc643
Revises: 4a972631e28d
Create Date: 2026-01-22 20:09:39.244207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff87ccadc643'
down_revision: Union[str, None] = '4a972631e28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite to handle adding column with foreign key
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chatmessage_chatsession_id', 'chatsession', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chatmessage_chatsession_id', type_='foreignkey')
        batch_op.drop_column('chat_session_id')
    # ### end Alembic commands ###